name: dev
on:
  ?
    - push
    - pull_request
  :
    branches:
      - dev
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@dev
    - uses: ./action-a
      env:
        MY_NAME: "Mona"