name: A workflow for my Hello World Action
on: push
jobs:
  build:
    name: Hewwo Worwd action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./actions-a
      env:
        MY_NAME: "MWOEP"